package ExceptionExample;

public class TryCatch {
	public static void main(String[] args) {
		try{
			int a = 0;
			int b = 20;
			
			int c = b/a;
			
			System.out.println(c);
		}
		
		catch(ArithmeticException e){
			System.out.println("Cannot divide number by zero");
		}
	}
}
